# Generated by Django 3.2.2 on 2021-05-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukrainian_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lab1_app.language')),
            ],
        ),
    ]
