# Generated by Django 3.2.2 on 2021-05-06 20:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='translate_to',
            new_name='translate_from',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 6, 20, 29, 22, 765568, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='learnt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='original',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
