# Generated by Django 3.2.2 on 2021-05-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_app', '0002_auto_20210506_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translate_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translate_to', to='lab1_app.language'),
        ),
        migrations.AlterField(
            model_name='word',
            name='translate_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translate_from', to='lab1_app.language'),
        ),
    ]
